version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/poc-fitterfly-backend/
hooks:
  ApplicationStop:
    - location: scripts/processkill
      timeout: 5
      runas: root
    - location: scripts/syskill
      timeout: 5
      runas: ubuntu
