version: 0.0
os: linux
#files:
#  - source: /index.html
#    destination: /var/www/html/
hooks:
        #  BeforeInstall:
        #    - location: scripts/gitpull
        #      timeout: 10
        #      runas: root
        #      #    - location: scripts/start_server
        #      #      timeout: 300
        #      #      runas: root
  ApplicationStop:
    - location: scripts/rails_start
      timeout: 10
      runas: root
    - location: scripts/gitpull
      timeout: 10
      runas: ubuntu
