version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/poc-fitterfly-backend/
permissions:    
  - object: /var/www/poc-fitterfly-backend
    pattern: "**"
    owner: ubuntu
    mode: 755
hooks:
  ApplicationStop:
    - location: scripts/processkill.sh
      timeout: 5
      runas: root
    - location: scripts/rvminstall.sh
      timeout: 5
      runas: ubuntu
